### ISSUE TITLE
Hero Component

### ISSUE THREAD

**Issue by manishprivet** [manishprivet/bookr#6]
We've to create a Hero Component for the Homepage, something like the Figma design in #5.

Note: This is a sub-issue of #2

**Comment by manishprivet** [comment]
PNG assets for this issue can be found [here](https://drive.google.com/drive/folders/15Yno457ZjtbPO2QpyKg162jux25sY1-i?usp=sharing).

**Comment by poorvi-vaish** [comment]
I'd like to work on this issue. Can you please assign it to me?
